In [11]:
# importing the libraries
import pandas as pd
from sklearn import linear_model,model_selection,metrics
import math

In [2]:
# load the data from csv
house_train=pd.read_csv('F:/DataSciencePractise/MachineLearningLab/datasets/HomePrice/train.csv')
house_test=pd.read_csv('F:/DataSciencePractise/MachineLearningLab/datasets/HomePrice/test.csv')

In [3]:
house_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
house_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
x_dims=['LotArea']
y_dims=['SalePrice']

In [7]:
X_train=house_train[x_dims]
y_train=house_train[y_dims]
X_test=house_test[x_dims]

In [9]:
lr=linear_model.Lasso()
lr.fit(X_train,y_train)

print("Coef : ",lr.coef_)
print("Intercept : ",lr.intercept_)

Coef :  [2.09997194]
Intercept :  [158836.15200251]

In [16]:
# estimators will have scoring funciton
# Resubstitution strategy. Score is calculated using explained variance
lr.score(X_train,y_train)
y_predict=lr.predict(X_train)
house_test['SalePrice']=lr.predict(X_test)

In [13]:
metrics.explained_variance_score(y_train,y_predict) # this is called train score

0.0696133153821119

In [15]:
meansqr=metrics.mean_squared_error(y_train,y_predict) # this is called train error
math.sqrt(meansqr)

76601.25405310983

In [17]:
house_test[['Id','SalePrice']].to_csv('laso_lotarea_submission.csv',index=False)